[workspace]
members = [
    "wuminbi",    # 中文注释：Wuminbi 手机端前端软件
    "wumiinapp",  # 中文注释：Wumiinapp 手机端前端软件
]

[dependencies]
core = { path = "../core" }
security = { path = "../security" }
storage = { path = "../storage" }
network = { path = "../network" }
interface = { path = "../interface" }
extension = { path = "../extension" }