[workspace]
members = [
    "init",
    "send_tx",
    "check_blocks",
]

[dependencies]
core = { path = "../core" }
security = { path = "../security" }
storage = { path = "../storage" }
network = { path = "../network" }
interface = { path = "../interface" }
extension = { path = "../extension" }